services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_RELATIVE_PATH: auth
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_LOG_LEVEL: INFO,org.keycloak.authentication:DEBUG
      KC_FEATURES: preview
    ports:
      - 8080:8080
      - 8443:8443
    command:
      - "--verbose"
      - "start-dev"

  keycloak-provisioning:
    image: quay.io/adorsys/keycloak-config-cli:5.2.0-18.0.0
    environment:
      KEYCLOAK_URL: http://keycloak:8080/auth
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: "true"
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: "120s"
# see: https://github.com/adorsys/keycloak-config-cli/blob/v5.0.0/CHANGELOG.md
      IMPORT_FILES_LOCATION: "/config/*" # IMPORT_PATH: "/config"
      IMPORT_CACHE_ENABLED: "true" # IMPORT_FORCE: "false"
      IMPORT_VAR_SUBSTITUTION_ENABLED: "true" # IMPORT_VARSUBSTITUTION: "true"
      IMPORT_VALIDATE: "true"

# See https://github.com/adorsys/keycloak-config-cli#log-level
#      LOGGING_LEVEL_KEYCLOAKCONFIGCLI: "debug"

    volumes:
      - ./acme-passwordless.yaml:/config/acme-passwordless.yaml:z